### ISSUE TITLE
Can we use uglify-es instead of uglify-js?

### ISSUE THREAD

**Issue by pigeonman99** [ForbesLindesay/browserify-middleware#117]
My javascript uses some ES6 features such as using "let" to declare a variable instead of "var". When in production mode, browserify-middleware works but was unable to minify/uglify my code. I suspect this is because browserify-middleware uses uglify-js which only support ES5.

Can we switch to uglify-es or give us an option to choose between uglify-js/uglify-es?

**Comment by ForbesLindesay** [comment]
I'd be happy to accept a pull request to upgrade to uglify-es

**Comment by pigeonman99** [comment]
pull request created: https://github.com/ForbesLindesay/browserify-middleware/pull/118
thanks!
