### ISSUE TITLE
How to use non-commonjs library with browserify?

### ISSUE THREAD

**Issue by gagan-bansal** [ForbesLindesay/browserify-middleware#20]
I want to use OpenLayers with borowserify-middleware, here are my code files [app.js](https://gist.github.com/gagan-bansal/6495291), [main.js](https://gist.github.com/gagan-bansal/6495476) and [index.html](https://gist.github.com/gagan-bansal/6495438)

I am able to display map properly, but there are few issues regarding the proper usage of browserify-middleware
- when downloaded in browser, main.js file size is double of the original files (main.js + OpenLayers.js), so it takes too much time to load. Why the file size is double? there is some encoded text at end of the file.
- how to define non-commonjs library as external? I followed the instructions as [here](https://gist.github.com/trevordixon/5747010) but could not achieve it. I have added {module.exports = OpenLayers} in the end of OpenLayers.js

**Comment by benjamingr** [comment]
@ForbesLindesay hey, any chance you could copy-paste your answer here: http://stackoverflow.com/questions/34962506/how-to-include-my-ownnon-moduled-scripts-using-browserify ? (Since you're an active SO user and all and you should get credit for it - excellent writeup btw)
