### ISSUE TITLE
Using reactify with the --es6 flag

### ISSUE THREAD

**Issue by rafaelchiti** [ForbesLindesay/browserify-middleware#46]
Hi sorry if it's an obvious question but I've been digging int he code that calls the transformers and can not see how to send this option to the transformer I'm using (reactify). Probable I need to configure the transformer in a different way but still not sure how to set the parameter.

This is my current code. How can I set options on that particular transformer?, is it possible the reactify API is not compatible for setting the option?.

The option I need to set is '--es6', which I guess will become {es6: true}

```
var browserify = require('browserify-middleware');
browserify.settings({
  transform: ['reactify'],
  extensions: ['.js', '.jsx'],
  grep: /\.jsx?$/
})
```

Thanks!

**Comment by nene** [comment]
Not silly at all. I was looking for the same thing. It's far from obvious to figure out from Reactify documentation.

**Comment by ForbesLindesay** [comment]
Perhaps one of you could add a pull request to make this library's documentation clearer?  Perhaps an extra example in the readme?

**Comment by svileng** [comment]
I was wondering the same thing, thanks for sharing your solution!

**Comment by kelunik** [comment]
Thanks for sharing!
