### ISSUE TITLE
{cache: 'dynamic'} no longer seems to work

### ISSUE THREAD

**Issue by ianwremmel** [ForbesLindesay/browserify-middleware#72]
With the following config, I get a full rebuild on every page load, even if no changes have been made:

```JavaScript
var assert = require('assert');
assert(process.env.NODE_ENV === 'development');

app.use('/scripts/', browserify('src/app/scripts/', {
  cache: 'dynamic',
  noParse: ['jquery'],
  transform: [
    'reactify',
    'envify',
  ],
}));
```

**Comment by scottbrady** [comment]
I upgraded from 3.0.1 to 5.0.0 and also starting seeing this bug.  I think the caching refactor might be the cause.

https://github.com/ForbesLindesay/browserify-middleware/commit/f3f366239f7024354d8141ebf3f9778d1ef8f78a

**Comment by ianwremmel** [comment]
I'm seeing the problem on 4.1.0
