### ISSUE TITLE
Display Javascript syntax errors

### ISSUE THREAD

**Issue by gionatan-lombardi** [ForbesLindesay/browserify-middleware#95]
Hi, if I have a JS syntax error the bundle file results in a pending status instead of 500.

It would be great to have the file in 500 with the JS error in the response or the error in the express's `next` function.

Thanx!

**Comment by ForbesLindesay** [comment]
You'll need to provide an example to reproduce this.

**Comment by gionatan-lombardi** [comment]
Hi, I watched deeply in my `express` setup and found an error handling bug.

Sorry for your time losing 😔
